### ISSUE TITLE
Unable to Reproduce Results as Stated in the Research Paper

### ISSUE THREAD

**Issue by mwaseemrandhawa** [music-x-lab/ISMIR2019-Large-Vocabulary-Chord-Recognition#1]
Hello,

I have attempted to reproduce the results stated in the research paper multiple times but have been unable to achieve the same performance.

**Comment by mwaseemrandhawa** [comment]
Finally I found the solution we just needed to convert the cqt to  db scale then we can produce the same resutls as described in the reserarch papper.

**Comment by world-better** [comment]
Can not get the same result when using same dataset and parameters to train. I find the same 1217 song dataset and use (1.0,20.0) to train the model. but the chord detection result is different from the  naive (1.0,20.0), for detailes, the naive model detect it as "N" while the trained one would show chord, and also some of chords properties aren't right. would you like to explain how to do the convert of cqt and db
